from __future__ import annotations

from pathlib import Path
from typing import Mapping


def _read_env_map(env_path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not env_path.exists():
        return values
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def ensure_client_env_file(
    *,
    defaults: Mapping[str, str],
    env_path: str | Path | None = None,
    service_label: str,
) -> Path:
    target = Path(env_path) if env_path is not None else (Path.cwd() / ".env")
    target.parent.mkdir(parents=True, exist_ok=True)

    existing = _read_env_map(target)
    missing_keys = [key for key in defaults.keys() if not existing.get(key)]
    if not missing_keys:
        return target

    lines: list[str]
    if target.exists():
        lines = target.read_text(encoding="utf-8").splitlines()
        if lines and lines[-1].strip():
            lines.append("")
    else:
        lines = [
            f"# Auto-generated by {service_label}",
            "# Fill the blank values, then rerun.",
            "",
        ]

    for key in missing_keys:
        value = defaults[key]
        lines.append(f"{key}={value}")

    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target


def upsert_client_env_values(
    *,
    values: Mapping[str, str],
    env_path: str | Path | None = None,
    service_label: str,
) -> Path:
    target = Path(env_path) if env_path is not None else (Path.cwd() / ".env")
    target.parent.mkdir(parents=True, exist_ok=True)
    existing = _read_env_map(target)
    for key, value in values.items():
        if value == "" and existing.get(key):
            continue
        existing[key] = value

    lines = [
        f"# Auto-generated by {service_label}",
        "# Update values as needed.",
        "",
    ]
    for key in sorted(existing.keys()):
        lines.append(f"{key}={existing[key]}")
    target.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return target
